### ISSUE TITLE
pkgaudit : use case insensitive check

### ISSUE THREAD

**Issue by zerwes** [Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-checkmk#11]
as sometimes just the notation changes
```yaml
curl:
  issues:
    - cURL -- Multiple vulnerabilities
    - curl -- Multiple vulnerabilities
```
